# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://NiehXiaoBin.github.io
date_format: "ordinal"
title: Nieh
subtitle: "Good Good Study, Day Day Up !!!"
description: "冰笑: NiehXiaoBin"
keywords: Nieh, 冰笑
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Nieh
organization:
organization_url:
github_username: NiehXiaoBin
location: RiZhao, China
email: NiehXiaoBin@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Index

  -
    href: /categories/
    label: Category

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: NiehXiaoBin/NiehXiaoBin.github.io

## ---------------- #
##      Comments    #
## ---------------- #
## support provider: disqus, gitment, gitalk
#comments_provider: gitalk
## !!!重要!!! 请修改下面这些信息为你自己申请的
## !!!Important!!! Please modify infos below to yours
## https://disqus.com
#disqus:
#    username:
## https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: JSnail
#    repo: JSnail.github.io
#    clientID: 36fb7ca4674e808981f9
#    clientSecret: cbe26b42dbaf83ccfdbd411f5801905a3d7dc210
#
#deploy:
#  type: git
#  branch: master
#  repo:
#    github: git@github.com:JSnail.coding.me/Snail
#    coding: git@git.coding.net:git.coding.net/JSnail/Snail.git
#
#
## 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
