# Site settings
title:          冰笑
description:    "NIce"
baseurl:        "/NIce"
url:            "https://niehxiaobin.github.io"

# Author
author:
  name:         NiehXiaoBin
  url:          https://niehxiaobin.github.io
  email:        NiehXiaoBin@163.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
